version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: fked
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - 3306:3306
    volumes:
    - ./data/mysql/data:/var/lib/mysql
    - ./mysql:/docker-entrypoint-initdb.d
